DROP TABLE IF EXISTS EmailAddress;
DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS School;
DROP TABLE IF EXISTS Advisor;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Team;
DROP TABLE IF EXISTS StudentTeam;
