TRUNCATE TABLE public.address
RESTART IDENTITY
CASCADE;
TRUNCATE TABLE public.advisor
RESTART IDENTITY
CASCADE;
TRUNCATE TABLE public.credential
RESTART IDENTITY
CASCADE;
TRUNCATE TABLE public.parking
RESTART IDENTITY
CASCADE;
TRUNCATE TABLE public.school
RESTART IDENTITY
CASCADE;
TRUNCATE TABLE public.school_advisor
RESTART IDENTITY
CASCADE;
TRUNCATE TABLE public.student
RESTART IDENTITY
CASCADE;
TRUNCATE TABLE public.team
RESTART IDENTITY
CASCADE;
TRUNCATE TABLE public.team_score
RESTART IDENTITY
CASCADE;
TRUNCATE TABLE public.session
RESTART IDENTITY
CASCADE;